{
 "title": "mockserver dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "canary test mock server wide metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "mock server request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by(service_name) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval]) * 60)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server request count not status 2xx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by(service_name) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\", http_status_code!~\"20*\"}[$__rate_interval])) * 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by req/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval]))) or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by not status 2xx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\", http_status_code!~\"^20.*\"}[$__rate_interval])) or vector(0)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by status code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "canary test mock server path metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "mock server by path  req/sec  ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by(service_name, span_name) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by path latency (99%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, span_name) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by path status code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by(http_status_code, span_name) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by path not status 200",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum by(http_status_code, span_name) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\", http_status_code!~\"^20.*\"}[$__rate_interval])) or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "mock server wide metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "mock server request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by(service_name) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\"}[$__rate_interval]) * 60)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server request count not status 2xx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum by(service_name) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\", http_status_code!~\"20*\"}[$__rate_interval])) * 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by req/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"flexiblemockserver\"}[$__rate_interval]))) or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"flexiblemockserver\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"flexiblemockserver\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by status code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by not status 2xx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\", http_status_code!~\"^20.*\"}[$__rate_interval])) or vector(0)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "mock server path metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "mock server by path  req/sec  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by(service_name, span_name) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mock server by path latency (99%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, span_name) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"flexiblemockserver\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mock server by path status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(http_status_code, span_name) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mock server by path not status 200",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(http_status_code, span_name) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\", http_status_code!~\"^20.*\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}