{
 "title": "mockserver dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "loadtest-metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "locust_requests_current_rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by(pod_name) (locust_requests_current_rps)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "locust_requests_current_fail_per_sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg by(pod_name) (locust_requests_current_fail_per_sec)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "canary test mock server wide metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "mock server request count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "sum by(service_name) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval]) * 60)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server request count not status 2xx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "targets": [
      {
       "expr": "sum by(service_name) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\", http_status_code!~\"20*\"}[$__rate_interval])) * 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by req/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "sum(rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval]))) or vector(0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by not status 2xx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\", http_status_code!~\"^20.*\"}[$__rate_interval])) or vector(0)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by status code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "canary test mock server path metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "mock server by path  req/sec  ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
     "targets": [
      {
       "expr": "sum by(service_name, span_name) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by path latency (99%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, span_name) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by path status code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
     "targets": [
      {
       "expr": "sum by(http_status_code, span_name) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "mock server by path not status 200",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
     "targets": [
      {
       "expr": "sum by(http_status_code, span_name) (rate(traces_spanmetrics_calls_total{service_name=\"canary-test-flexiblemockserver\", http_status_code!~\"^20.*\"}[$__rate_interval])) or vector(0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "flagger metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "progressive delivery status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
     "targets": [
      {
       "expr": "avg by(name) (flagger_canary_status{name=\"canary-test-flexiblemockserver\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "istio weight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
     "targets": [
      {
       "expr": "avg(flagger_canary_weight{workload=\"canary-test-flexiblemockserver-primary\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(flagger_canary_weight{workload=\"canary-test-flexiblemockserver\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "mock server wide metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "mock server request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(service_name) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\"}[$__rate_interval]) * 60)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mock server request count not status 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by(service_name) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\", http_status_code!~\"20*\"}[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mock server by req/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mock server by latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"flexiblemockserver\"}[$__rate_interval]))) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"flexiblemockserver\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"flexiblemockserver\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mock server by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mock server by not status 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\", http_status_code!~\"^20.*\"}[$__rate_interval])) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "mock server path metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "mock server by path  req/sec  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(service_name, span_name) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mock server by path latency (99%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, span_name) (rate(traces_spanmetrics_duration_milliseconds_bucket{service_name=\"flexiblemockserver\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mock server by path status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by(http_status_code, span_name) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mock server by path not status 200",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum by(http_status_code, span_name) (rate(traces_spanmetrics_calls_total{service_name=\"flexiblemockserver\", http_status_code!~\"^20.*\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mockserver namespace k8s resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "mockserver CPU resource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(exported_pod) (kube_pod_container_resource_limits{pod=~\".+\", resource=\"cpu\", unit=\"core\", exported_namespace=\"mockserver\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(exported_pod) (kube_pod_container_resource_requests{pod=~\".+\", resource=\"cpu\", unit=\"core\", exported_namespace=\"mockserver\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mockserver Memory resource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(exported_pod) (kube_pod_container_resource_limits{pod=~\".+\", resource=\"memory\", unit=\"byte\", exported_namespace=\"mockserver\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(exported_pod) (kube_pod_container_resource_requests{pod=~\".+\", resource=\"memory\", unit=\"byte\", exported_namespace=\"mockserver\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mockserver namespace running pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 55 },
   "targets": [
    {
     "expr": "sum by() (kube_pod_status_phase{phase=\"Running\", exported_namespace=\"mockserver\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{exported_namespace=\"mockserver\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{exported_namespace=\"mockserver\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}