# kustmize.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - role.yaml
  - role_binding.yaml
  - service_account.yaml
  - service_monitor.yaml
  - prometheus_service.yaml
