apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-sample
  namespace: mockserver
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: flexiblemockserver
  remoteWrite:
  - url: "http://prometheus-operated.mockserver:9090/api/v1/write"
  containers:
  - name: prometheus
    args:
    - "--config.file=/etc/prometheus/prometheus.yml" # 設定ファイルの正しいパス
    - "--storage.tsdb.path=/prometheus"
    - "--web.console.libraries=/etc/prometheus/console_libraries"
    - "--web.console.templates=/etc/prometheus/consoles"
    - "--web.enable-remote-write-receiver"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: mockserver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mockserver
  name: prometheus-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: mockserver
  name: prometheus-rolebinding
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: mockserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-role
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-sample
  namespace: mockserver
  labels:
    team: flexiblemockserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: simplest1-collector
  endpoints:
  - port: otlp-grpc
    interval: 30s
