apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-sample
  namespace: mockserver
spec:
  replicas: 1
  serviceAccountName: prometheus
  enableRemoteWriteReceiver: true
  serviceMonitorSelector: {}
