apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: locust-operator-role
rules:
- apiGroups: ["locust.io"]
  resources: ["locusttests"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: locust-operator-binding
subjects:
- kind: ServiceAccount
  name: locust-operator-locust-k8s-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: locust-operator-role
  apiGroup: rbac.authorization.k8s.io
