# cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
    - containerPort: 8080
      hostPort: 30000
      protocol: TCP
    - containerPort: 3000
      hostPort: 30001
      protocol: TCP
    - containerPort: 9411
      hostPort: 30002
      protocol: TCP
    - containerPort: 9412
      hostPort: 30003
      protocol: TCP
- role: worker
- role: worker
