# kustmize.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-grafana
resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- namespace.yaml
configMapGenerator:
  - name: grafana-config
    files:
      - config/datasources.yaml
  - name: grafana-dashboards
      - config/dashboards.yaml
      - config/mockserver.json
