# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flexiblemockserver
  namespace: mockserver
spec:
  selector:
    app: flexiblemockserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
