# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flexiblemockserver
  namespace: mockserver
spec:
  selector:
    app: flexiblemockserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
    - port: 15020
      targetPort: 15020
  type: NodePort
