apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: simplest
  namespace: my-tempo
spec:
  storage:
    secret:
      name: minio-test
      type: s3
  storageSize: 1Gi
  resources:
    total:
      limits:
        memory: 4Gi
        cpu: 4000m
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true

