# cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # TODO: If you do not want access from outside clusters, comment this out.
  extraPortMappings:
    - containerPort: 30000
      hostPort: 8081
      protocol: TCP
    - containerPort: 30001
      hostPort: 3001
      protocol: TCP
    - containerPort: 30002
      hostPort: 3002
      protocol: TCP
    - containerPort: 30003
      hostPort: 3003
      protocol: TCP
- role: worker
- role: worker
- role: worker
