# kustmize.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loadtest
resources:
- locusttest.yaml
configMapGenerator:
  - name: demo-test-map2
    files:
      - demo_test.py
generatorOptions:
  disableNameSuffixHash: true
